language: cpp
os: linux
dist: bionic
sudo: yes

compiler:
  - clang

addons:
  apt:
    packages: libncurses5-dev libgoogle-perftools-dev

install:
  - |
    git clone --depth 1 --branch libpcap-1.9.1 https://github.com/the-tcpdump-group/libpcap.git
    mkdir -p libpcap/build && cd libpcap/build
    cmake ../ -DBUILD_SHARED_LIBS=0
    make
    sudo make install
    cd -

  - |
    git clone --depth 1 --branch 6.1.2 https://github.com/fmtlib/fmt.git
    mkdir -p fmt/build && cd fmt/build
    cmake ../ -DFMT_TEST=off
    make
    sudo make install
    cd -

  - |
    git clone --depth 1 https://github.com/mfontanini/libtins.git
    mkdir -p libtins/build && cd libtins/build
    cmake ../ -DLIBTINS_BUILD_SHARED=0 -DLIBTINS_ENABLE_CXX11=1 -DLIBTINS_ENABLE_WPA2=0
    make
    sudo make install
    cd -

  - |
    git clone --depth 1 https://github.com/catchorg/Catch2.git
    mkdir -p Catch2/build && cd Catch2/build
    cmake ../ -DCATCH_BUILD_TESTING=off -DCATCH_INSTALL_DOCS=off -DCATCH_INSTALL_HELPERS=off
    make
    sudo make install
    cd -

  - |
    git clone --depth 1 --branch v1.5.0 https://github.com/gabime/spdlog.git;
    mkdir -p spdlog/build && cd spdlog/build
    cmake ../ -DSPDLOG_FMT_EXTERNAL=on -DSPDLOG_BUILD_TESTS=off
    make
    sudo make install
    cd -

script:
  - |
    mkdir -p build && cd build
    cmake -DBUILD_STATICS_EXEC=on -DENABLE_TESTS=on ..
    make
    ctest

deploy:
  provider: releases
  api_key:
    secure: "p+mwkt1O0TAhoNZLwQb1sAfelZI6bqE4KylrKc8kN6CI/HPDVOq213EC4RFEZ1jKvI0youw9oQ9ixrVr+R29JoEy+eyJKiLqrVxD1r+P6vrxX9bpSnvvDPvce1yQmlSTByy3bXbaAf81edP3bcSDQVqJoMsUgTyfikFu5EFqUM/H9TiOD119wxug5EtgtnHhZWMXdIYQZNnwdAqRoxG8eErscS52gaQOarIqb46s814pTc+O7EtHv07sDJPV7UfJD45rMRtl4A0G4+j6rvpj4HqYwlsXFIduCokU/OBBXy2WDhzEokZysMNTQWdbKqUq8/IzoZu7/G75IGGxxapjYtWGf1LuWzKAZ68+Vphtb2mstJrUJLiWsN9sGUnPM8USGr7lqCpNm8TIPhal3Su2F2e5A/GWKUjr42M8b0+/vFPjRSwifE2tf4x9qf68J+dTbkN/suePUsZFhy9/SHcmhoPvwfwcKzA/fMfSFygiAZuxTxXri8GM6rI8OwzLD8wexpbR8lURm96J59eKExvSu6rsNOx/hg7Q4lsgdnoqoBgrr0qpBubHhS8WvWZcG6Ocp4wUupj5Pbni7mHhYkpHAR+6CN7nhR96axT6MZa+9wRWpdD8il67/MnOX3H8HjOKhJUL0KITf+BrdbJ2VcEZXQrYhT9cutySVHlFWzKlNps="
  file: "src/flowstats"
  skip_cleanup: true
  on:
    tags: true
