language: cpp
os: linux
dist: bionic
sudo: yes

compiler:
  - clang

env:
  global:
    # Coverity token
    - secure: "sexBL5TdobE01HXCdVYsYjD60+miD6E3+pU23fngPqwm3N0sOerfnyoSqNjfUyryAnPm6xxKQ37WbngBp/VwKzyEONxMKItZY1avKsaU5yvF3SDbWF6upYhrnVoSqS1QHqNog6zj5cT2LwrQzdhY5QACGGnTuHsv85fgneA0V0vvoQtBB3tijmVtb6EWquXOvfbQcRXI0Wa4nAlMpIpZqTCKCzCBtPvc4gi0mu/kcS7rsAjtkuQ3Pwy3Y+RsB3sJuJcn8FvcCOW2Y4kV+Z3fetZbBVxzMFbrUFxbdJxCr3kQqTzX7PkSCOjchpOGm349L3AzP+lMCKKctO98mymhtIZKVVybV0D2gTZoifiSeKT8YXa7AbnweNNHBQxcAbMwKbr5Ve/9+4Ye8B6/Eqale45ZBph3q4qoenP5R1Y0fE18EspFbYMFhBrAG3mB7SxTIK74kTZdQ8Evvby2sWWHlxQDuGSa2+DE+n1reJiUsUdKPtHF9X4X7YQvqcn+KywHtFcxL7ICa4uFJTNRPGG+0yUAPux6uf+poV1igQVIutEiD/JzNGyB6au+4YFVT1xU+N12TH0lPWfeePJdGzfItset31a3MnjvYchfAPvZLmeZFkLptsPX3xST26dEEcIlHuWUtez41SLH/D0WZcpxVmkYXeQuk4bfROiP3k4k66M="

addons:
  apt:
    packages: libncurses5-dev libgoogle-perftools-dev
  coverity_scan:
    project:
      name: "bonnefoa/flowstats"
      description: "Flowstats"
    notification_email: anthonin.bonnefoy@gmail.com
    build_command_prepend: "mkdir build; cd build; cmake .. -DENABLE_TESTS=on"
    build_command: "make -j2"
    branch_pattern: coverity_scan

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - |
    git clone --depth 1 --branch libpcap-1.9.1 https://github.com/the-tcpdump-group/libpcap.git
    mkdir -p libpcap/build && cd libpcap/build
    cmake ../ -DBUILD_SHARED_LIBS=0
    make -j2
    sudo make install
    cd -

  - |
    git clone --depth 1 --branch 6.1.2 https://github.com/fmtlib/fmt.git
    mkdir -p fmt/build && cd fmt/build
    cmake ../ -DFMT_TEST=off
    make -j2
    sudo make install
    cd -

  - |
    git clone --depth 1 https://github.com/mfontanini/libtins.git
    mkdir -p libtins/build && cd libtins/build
    cmake ../ -DLIBTINS_BUILD_SHARED=0 -DLIBTINS_ENABLE_CXX11=1 -DLIBTINS_ENABLE_WPA2=0
    make -j2
    sudo make install
    cd -

  - |
    git clone --depth 1 --branch v2.12.1 https://github.com/catchorg/Catch2.git
    mkdir -p Catch2/build && cd Catch2/build
    cmake ../ -DCATCH_BUILD_TESTING=off -DCATCH_INSTALL_DOCS=off -DCATCH_INSTALL_HELPERS=ON
    make -j2
    sudo make install
    cd -

  - |
    git clone --depth 1 --branch v1.5.0 https://github.com/gabime/spdlog.git;
    mkdir -p spdlog/build && cd spdlog/build
    cmake ../ -DSPDLOG_FMT_EXTERNAL=on -DSPDLOG_BUILD_TESTS=off
    make -j2
    sudo make install
    cd -

script:
  - |
    mkdir -p build && cd build
    cmake -DBUILD_STATIC_EXE=on -DENABLE_TESTS=on ..
    make -j2
    ctest

deploy:
  provider: releases
  api_key:
    secure: "RhHhEkwOdMtIFaFjX+m6A4aJWucQ7esTPFm/0M/BEw2oiutYAMTKNqw+TiQ7J7j7yJd7RbVYRPb4u94x27+Wlety1gSQFsY5kjiyYpqk6yYGj8WsEQRdGcs4C47OUc3STA44CdXZ34rqjUnIg0FottU0eqX1ZyFeuHYNzuwkrb3rUCqJ9FDLpTa2MhgXemQYQNKNQkJteWrQqb+l0BCeAFOamCgezl92/h1X2QVIwPQl6vyH/pL7lbErHGXPgtYFbDAHDEkqkaTdRelBfj8kg1PP+u5rKVx0XzTz3QRJgnXivGpkzWkLmTSJG8IDnNN8AJRPCgKcX6Q+AbcOtWfo/8WEz3Pbs1xwxgzGB+bjEt2xN3gmcwf/ll3b6soZKCO900vxZhGP6oyqops5A5IKCDz6zz4XASAHSj7PS+hPNlKY1Nq+Sll3VMLEVk6EqpUh3aZ485vtyl0GHj5sU7oqGSBY5wJKnyOloQ2YPFo7vGkS82lX9bzhBPQWEN7/iAckKeHleU4Gi6MhrdMmRvLjqRNz/h2ps+5rqYEldM92ygTM4DR/QYFN8EC6EMm6RE5D5mpyOfUPcpCS0m+8zX1vBzsyjfYqoUMQwHCzWhcP6jY4T9Yin28qPF+qyCim+ueGZZjcpG8/pSfuRzN4Y6T5i6psn7SxfpV2lRclB9FbrUY="
  file: "src/flowstats"
  skip_cleanup: true
  on:
    tags: true
